Switch Documenter.jl math engine to MathJax3
CliMA/Oceananigans.jl pull request #1530
Opened 2021-03-31 18:03 UTC by ali-ramadhan

Documenter.jl uses KaTeX by default but MathJax3 might be better for us. Will wait for Buildkite to build and deploy the docs to see 🤞 

Resolves #528 (hopefully)

2021-03-31 20:05 UTC, glwagner approved these changes

2021-03-31 20:05 UTC, glwagner commented on docs/make.jl
> +       mathengine = MathJax3()
It's that easy!

2021-03-31 20:27 UTC, navidcy commented
Did you view the preview docs?

2021-03-31 20:35 UTC, glwagner commented
> Did you view the preview docs?

Ah, doesn't look great...

![Uploading image.png…]()

2021-03-31 20:36 UTC, glwagner requested changes
Ok, this probably can't be merged because it looks like this

![image](https://user-images.githubusercontent.com/15271942/113207904-0a0d7a00-9226-11eb-9c1b-31e72e715a5b.png)

2021-03-31 21:22 UTC, navidcy commented on docs/make.jl
> +       mathengine = MathJax3()
I doubted it would be

2021-03-31 21:34 UTC, ali-ramadhan commented
Ah it was just a try. `\bm` comes from the `bm` LaTeX package which I guess was available with KaTeX. For MathJax we might have to define the `\bm` command at the top of the pages that use it?

[Equation numbering still doesn't work](https://clima.github.io/OceananigansDocumentation/previews/PR1530/numerical_implementation/time_stepping/) but apparently it's because MathJax3 doesn't enable it by default: http://docs.mathjax.org/en/latest/input/tex/eqnumbers.html

Looks like we can configure it by passing a dict to the `MathJax3` constructor though: https://juliadocs.github.io/Documenter.jl/stable/lib/internals/writers/#Documenter.Writers.HTMLWriter.MathJax3

2021-04-01 22:45 UTC, navidcy commented
I started fixing it. Seems like `\underbrace{}` doesn't compile in MathJax3... A quick googling didn't reveal any solutions. Will try to look into it later and continue. :)

2021-04-09 21:48 UTC, navidcy commented
@ali-ramadhan, I believe this is working now. There are some issues when referencing other sections of the docs, but perhaps let's leave that for a future PR? Equation numbering **within each `.md` file** works now!

2021-04-09 23:43 UTC, navidcy commented
hm... I merged master and the unit tests seem to fail saying

```julia

[2021/04/09 19:34:17.876] WARN  Checksum did not match -@-> /storage7/buildkite-agent/.julia-1983/packages/DataDeps/ooWXe/src/verification.jl:24
--
  | Do you wish to Abort, Retry download or Ignore
  | [a/r/i]
```

Apparently buildkite is not answering so tests stop at that point indefinitely...

https://buildkite.com/clima/oceananigans/builds/1983#a259cdda-aa8b-40f1-861f-e198c1e7c7f2

2021-04-12 14:45 UTC, ali-ramadhan commented
@navidcy Ah sorry about that error, it was fixed in PR #1552. I merged `master` into this branch which should fix the unit tests.

2021-04-12 21:15 UTC, navidcy commented
hm... tests pass here after 3-4 days!
weird.
seems like just something made the code extremely slow?

2021-04-12 23:33 UTC, glwagner commented
None of the individual test runs took very long, but our CI pipeline is clogged up due to this hanging issue.

2021-04-13 23:30 UTC, ali-ramadhan commented
Looks like this PR upgrades to Julia 1.6 as well now?

2021-04-14 00:10 UTC, navidcy commented
Yes.... it was part of my attempts to de-clog everything.
But I'm thinking to revert those changes!

2021-04-14 01:02 UTC, navidcy commented on .gitignore
> -docs/Manifest.toml
@ali-ramadhan should `docs/Manifest.toml` be in the `.gitignore` or was I right to take it ou?

2021-04-14 02:19 UTC, navidcy commented
OK. We have a preview!

https://clima.github.io/OceananigansDocumentation/previews/PR1530/

@ali-ramadhan, could you have a look?

2021-04-14 02:20 UTC, navidcy approved these changes
I'm approving here but I made so many changes that, in principle, I should be asking for others to review this :)

2021-04-14 02:24 UTC, navidcy commented
We have a preview at https://clima.github.io/OceananigansDocumentation/previews/PR1530/ which revealed some latexing issues... I'll get to them :)

2021-04-14 11:51 UTC, navidcy commented
See the preview @ https://clima.github.io/OceananigansDocumentation/previews/PR1530/

2021-04-14 12:01 UTC, ali-ramadhan commented
Thanks so much @navidcy for putting all this work into making the docs beautiful again!

I guess I can't approve this PR since I opened it but here's a thumbs up 👍 PR needs @glwagner's approval since he requested changes I think.

2021-04-14 12:07 UTC, navidcy commented
I don't think @glwagner requested anything.

There are still some links in the docs that are broker (e.g., couple refs to eqs that don't exist). With MathJax3 `\label{..}` and `\eqref{..}` works *but only within the same page*. I tried to minimise referencing equations from other pages but there may be still some left. I'll fix them in a different PR though, together with some links to sections that may not exist anymore. We should do any refs to other docs sections via Documenter's functionality so then it'll complain when something breaks.

2021-04-14 12:19 UTC, francispoulin commented on docs/src/appendix/fractional_step.md
> +Solving the momentum equation \eqref{eq:momentumFV} coupled with the continuity equation can
I see this is where the referencing to equations does not work.  I am fine with having this fixed in another PR if that's easier.

2021-04-14 12:20 UTC, ali-ramadhan commented
That makes sense. Will make sure to use Documenter.jl's referencing for referencing across pages.

> I don't think @glwagner requested anything.

Ah I thought merging is blocked right now because someone requested changes in their PR review. Maybe I'm seeing something different as the one who opened the PR though.

![image](https://user-images.githubusercontent.com/20099589/114709078-25828580-9cfa-11eb-891b-8eb5f0186bef.png)

2021-04-14 12:24 UTC, navidcy commented
oh yes...

@glwagner we hereby request your re-review and, hopefully, your approval.

2021-04-14 12:37 UTC, francispoulin approved these changes
An impressive number of changes @navidcy, very well done!  Everything looks good to me except the referencing the equations that you mentinoed.  Also, @ali-ramadhan had a comment and not sure if that discussion was resolved or not.

2021-04-14 12:41 UTC, navidcy commented
thanks @francispoulin
regarding @ali-ramadhan's remark: yeap, I've reverted the Julia v1.6 transition.

2021-04-14 12:43 UTC, ali-ramadhan commented
Woah did not know you could do this :eyes:

![image](https://user-images.githubusercontent.com/20099589/114711894-7ba4f800-9cfd-11eb-9d78-0b64ecb855fe.png)

2021-04-14 12:45 UTC, navidcy commented
> Woah did not know you could do this 👀
> 
> ![image](https://user-images.githubusercontent.com/20099589/114711894-7ba4f800-9cfd-11eb-9d78-0b64ecb855fe.png)

I didn't know either! But I saw the button and thought it was appropriate at this point so I'd give it a go.
@glwagner didn't even specify what changes needed to be made! haha

2021-04-14 13:49 UTC, merged