Eliminate VerticallyStretched and Regular RectilinearGrid
CliMA/Oceananigans.jl pull request #2050
Opened 2021-11-10 18:30 UTC by simone-silvestri

eliminate the previous rectilinear grids in favour of a general RectilinearGrid which can be stretched in any direction

2021-11-10 18:44 UTC, glwagner commented
Completely mind blowing

2021-11-10 22:13 UTC, simone-silvestri commented
On a better look, I need to change the docs before

2021-11-11 06:45 UTC, navidcy approved these changes

2021-11-11 06:53 UTC, navidcy commented on src/Grids/rectilinear_grid.jl
>  function RectilinearGrid(FT = Float64;
@simone-silvestri, I think we need a docstring here before merging this PR.

See, for example, the docstring for `RegularRectiliniarGrid`:
https://github.com/CliMA/Oceananigans.jl/blob/24e766481cebbc8f61099b386623d175218acedb/src/Grids/regular_rectilinear_grid.jl#L37-L153

2021-11-11 06:53 UTC, navidcy requested changes
add docstring?

2021-11-11 08:22 UTC, navidcy commented
These two tests should be failing...

https://github.com/CliMA/Oceananigans.jl/blob/77693f7d5dad1e5f8a90c13a2dcd13b8db2e1f71/test/test_rectilinear_grid.jl#L146-L147

Wait. Is `test_rectilinear_grid.jl` ever being called in tests? I'm bit confused...

2021-11-11 08:53 UTC, navidcy commented
@simone-silvestri I think this PR needs bump up version to 0.66

2021-11-11 09:58 UTC, navidcy commented
ShallowWater example fails in docs. 

```julia
julia> simulation.output_writers[:fields] = NetCDFOutputWriter(model, (; ω, ω′),
                                                               filepath = joinpath(@__DIR__, "shallow_water_Bickley_jet_fields.nc"),
                                                               schedule = TimeInterval(1),
                                                               mode = "c")
ERROR: type StepRangeLen has no field parent
Stacktrace:
 [1] getproperty(x::StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}, f::Symbol)
   @ Base ./Base.jl:33
 [2] default_dimensions(output::Dict{String, ComputedField{Face, Face, Center, Oceananigans.Fields.FieldStatus{Float64}, O, CPU, OffsetArrays.OffsetArray{Float64, 3, Array{Float64, 3}}, RectilinearGrid{Float64, Periodic, Bounded, Flat, Float64, Float64, Float64, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}, CPU}, Float64, FieldBoundaryConditions{BoundaryCondition{Oceananigans.BoundaryConditions.Periodic, Nothing}, BoundaryCondition{Oceananigans.BoundaryConditions.Periodic, Nothing}, Nothing, Nothing, Nothing, Nothing, BoundaryCondition{Oceananigans.BoundaryConditions.Flux, Nothing}}} where O}, grid::RectilinearGrid{Float64, Periodic, Bounded, Flat, Float64, Float64, Float64, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}, CPU}, field_slicer::FieldSlicer{Colon, Colon, Colon})
   @ Oceananigans.OutputWriters ~/Research/OC2/src/OutputWriters/netcdf_output_writer.jl:39
 [3] NetCDFOutputWriter(model::ShallowWaterModel{RectilinearGrid{Float64, Periodic, Bounded, Flat, Float64, Float64, Float64, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}, CPU}, CPU, Float64, WENO5, FPlane{Float64}, NamedTuple{(:uh, :vh, :h), Tuple{typeof(Oceananigans.Forcings.zeroforcing), typeof(Oceananigans.Forcings.zeroforcing), typeof(Oceananigans.Forcings.zeroforcing)}}, Nothing, Nothing, NamedTuple{(:uh, :vh, :h), Tuple{Field{Face, Center, Center, CPU, OffsetArrays.OffsetArray{Float64, 3, Array{Float64, 3}}, RectilinearGrid{Float64, Periodic, Bounded, Flat, Float64, Float64, Float64, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}, CPU}, Float64, FieldBoundaryConditions{BoundaryCondition{Oceananigans.BoundaryConditions.Periodic, Nothing}, BoundaryCondition{Oceananigans.BoundaryConditions.Periodic, Nothing}, BoundaryCondition{Oceananigans.BoundaryConditions.Flux, Nothing}, BoundaryCondition{Oceananigans.BoundaryConditions.Flux, Nothing}, Nothing, Nothing, BoundaryCondition{Oceananigans.BoundaryConditions.Flux, Nothing}}}, Field{Center, Face, Center, CPU, OffsetArrays.OffsetArray{Float64, 3, Array{Float64, 3}}, RectilinearGrid{Float64, Periodic, Bounded, Flat, Float64, Float64, Float64, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}, CPU}, Float64, FieldBoundaryConditions{BoundaryCondition{Oceananigans.BoundaryConditions.Periodic, Nothing}, BoundaryCondition{Oceananigans.BoundaryConditions.Periodic, Nothing}, BoundaryCondition{Oceananigans.BoundaryConditions.Open, Nothing}, BoundaryCondition{Oceananigans.BoundaryConditions.Open, Nothing}, Nothing, Nothing, BoundaryCondition{Oceananigans.BoundaryConditions.Flux, Nothing}}}, Field{Center, Center, Center, CPU, OffsetArrays.OffsetArray{Float64, 3, Array{Float64, 3}}, RectilinearGrid{Float64, Periodic, Bounded, Flat, Float64, Float64, Float64, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}, CPU}, Float64, FieldBoundaryConditions{BoundaryCondition{Oceananigans.BoundaryConditions.Periodic, Nothing}, BoundaryCondition{Oceananigans.BoundaryConditions.Periodic, Nothing}, BoundaryCondition{Oceananigans.BoundaryConditions.Flux, Nothing}, BoundaryCondition{Oceananigans.BoundaryConditions.Flux, Nothing}, Nothing, Nothing, BoundaryCondition{Oceananigans.BoundaryConditions.Flux, Nothing}}}}}, NamedTuple{(), Tuple{}}, Nothing, Oceananigans.TimeSteppers.RungeKutta3TimeStepper{Float64, NamedTuple{(:uh, :vh, :h), Tuple{Field{Face, Center, Center, CPU, OffsetArrays.OffsetArray{Float64, 3, Array{Float64, 3}}, RectilinearGrid{Float64, Periodic, Bounded, Flat, Float64, Float64, Float64, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}, CPU}, Float64, FieldBoundaryConditions{BoundaryCondition{Oceananigans.BoundaryConditions.Periodic, Nothing}, BoundaryCondition{Oceananigans.BoundaryConditions.Periodic, Nothing}, BoundaryCondition{Oceananigans.BoundaryConditions.Flux, Nothing}, BoundaryCondition{Oceananigans.BoundaryConditions.Flux, Nothing}, Nothing, Nothing, BoundaryCondition{Oceananigans.BoundaryConditions.Flux, Nothing}}}, Field{Center, Face, Center, CPU, OffsetArrays.OffsetArray{Float64, 3, Array{Float64, 3}}, RectilinearGrid{Float64, Periodic, Bounded, Flat, Float64, Float64, Float64, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}, CPU}, Float64, FieldBoundaryConditions{BoundaryCondition{Oceananigans.BoundaryConditions.Periodic, Nothing}, BoundaryCondition{Oceananigans.BoundaryConditions.Periodic, Nothing}, Nothing, Nothing, Nothing, Nothing, BoundaryCondition{Oceananigans.BoundaryConditions.Flux, Nothing}}}, Field{Center, Center, Center, CPU, OffsetArrays.OffsetArray{Float64, 3, Array{Float64, 3}}, RectilinearGrid{Float64, Periodic, Bounded, Flat, Float64, Float64, Float64, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}, CPU}, Float64, FieldBoundaryConditions{BoundaryCondition{Oceananigans.BoundaryConditions.Periodic, Nothing}, BoundaryCondition{Oceananigans.BoundaryConditions.Periodic, Nothing}, BoundaryCondition{Oceananigans.BoundaryConditions.Flux, Nothing}, BoundaryCondition{Oceananigans.BoundaryConditions.Flux, Nothing}, Nothin [...]

2021-11-11 15:49 UTC, glwagner commented
Use parent(a) instead of a.parent. Also coordinates should include halos I think.

2021-11-11 19:32 UTC, navidcy commented
Possibly merging this PR means that we can close #1532? @francispoulin?

2021-11-11 19:47 UTC, navidcy commented
@simone-silvestri shall I give a go writing a docstring?

2021-11-11 19:48 UTC, navidcy commented
> Also coordinates should include halos I think.

Don't they now? I see `field_slicer.with_halos`...
Perhaps we leave this for a different PR? Perhaps @glwagner you raise an issue?

2021-11-11 20:13 UTC, francispoulin commented
> Possibly merging this PR means that we can close #1532? @francispoulin?

Very good point.  I will do that right now.  Thanks!

2021-11-11 20:45 UTC, simone-silvestri commented
@navidcy If you want and have time you are welcome! Otherwise I can do it later

2021-11-11 21:26 UTC, navidcy commented
@simone-silvestri, I'm trying to understand how I build a stretched grid using the `RectilinearGrid` constructor. I can pass an array or function to, e.g., keyword argument `z = ...`. But it's not clear what would the constructor do. Will it take that array or function and construct the faces of `z` or the centers?

2021-11-11 21:30 UTC, simone-silvestri commented
@navidcy A direction will be "stretched" if a vector or function is passed as an argument (just as the previous verticallystretchedgrid). In that case the vector (or function of i or j or k) must represent the location of the faces of the specified coordinate. In this case the spacings will be vectors. If a tuple is passed as an argument the coordinate will be "regular", i.e. the associated `Δᶜ` and `Δᶠ` will be scalars. If the keyword `extent` is specified, all directions will be regular.

2021-11-11 21:33 UTC, navidcy commented
> must represent the location of the faces of the specified coordinate

OK great. I wasn't sure for that! Thanks.

2021-11-11 21:53 UTC, navidcy commented
@simone-silvestri have a look at 73eb539 and modify if you feel is needed.

2021-11-11 21:55 UTC, navidcy commented
This PR is good improvement!

2021-11-11 22:10 UTC, simone-silvestri commented
> @simone-silvestri have a look at [73eb539](https://github.com/CliMA/Oceananigans.jl/commit/73eb5398789cad86a7b6df3da550c52630d7f8cb) and modify if you feel is needed.

Thanks @navidcy, very nice docstring!

2021-11-12 03:00 UTC, tomchor approved these changes

2021-11-12 03:10 UTC, navidcy commented on examples/ocean_wind_mixing_and_convection.jl
> +                                          z = z_faces)
Nice point

2021-11-12 13:28 UTC, simone-silvestri commented
@navidcy you're right. That file is a left over from the previous PR. I was using it to test `RectilinearGrid` while `RegularRectilinearGrid` and `VerticallyStretchedRectilinearGrid` were still around. Now it is basically the same as test_grids.jl. I will delete it

2021-11-12 16:46 UTC, glwagner commented on examples/ocean_wind_mixing_and_convection.jl
> +                          z = z_faces)
<3

2021-11-12 16:53 UTC, glwagner approved these changes
I'm amazed. Merge!

2021-11-12 16:55 UTC, glwagner commented
@navidcy looks like we need you to approve (because you requested changes) to merge.

2021-11-12 16:56 UTC, glwagner commented
Note to self: we should figure out an interface to help users access grid metrics. We shouldn't write things like `grid.Δxᵃᵃᶜ` in the examples.

2021-11-12 23:29 UTC, navidcy commented
> Note to self: we should figure out an interface to help users access grid metrics. We shouldn't write things like `grid.Δxᵃᵃᶜ` in the examples.

Yes yes yes!

Can we have alias?

2021-11-13 00:28 UTC, navidcy approved these changes
Approving with all my heart

2021-11-13 00:54 UTC, glwagner commented
> > Note to self: we should figure out an interface to help users access grid metrics. We shouldn't write things like `grid.Δxᵃᵃᶜ` in the examples.
> 
> Yes yes yes!
> 
> Can we have alias?

We need a function like `dx = grid_spacing(grid, 1)` or something which returns a number (if constant) or a field (if not).

2021-11-14 21:05 UTC, merged

2021-11-15 23:40 UTC, glwagner commented
@simone-silvestri it looks like the GPU solver tests and GPU regression tests now take about 4 hours. Is this right? Is there any way to speed it up? We could split the regression tests into multiple parts, perhaps. I think this might've been the last time our CI ran on the GPU...

2021-11-16 16:10 UTC, glwagner commented
Let's keep an eye on it!