Solver for nonhydrostatic IBG
CliMA/Oceananigans.jl pull request #2780
Opened 2022-10-17 18:22 UTC by simone-silvestri

cc @tomchor

2022-10-17 18:49 UTC, glwagner requested changes
Let's use PreconditionedConjugateGradientSolver with an FFT-based preconditioner (ie the original FFT solver) for this.

2022-10-19 15:07 UTC, tomchor commented
> Let's use PreconditionedConjugateGradientSolver with an FFT-based preconditioner (ie the original FFT solver) for this.

Can you explain a bit the reason for this choice, just so that I can understand better? At first it seems to me that using a FFT-based preconditioner would still produce Gibbs phenomenon effects in situations where the original FFT-based solver also would, no?

2022-10-19 18:00 UTC, glwagner commented
Is it the pressure field that has oscillations, or the velocity field?

Either way, I don't think that's important. A preconditioner should be some kind of approximate inverse for A, where we are solving for x in Ax = b --- or in other words, an approximate solver. The preconditioner does not have to be "exact" or "error free", since it's really the CG iteration that solves the problem. The idea is that the FFT-based solver yields a pressure field that is _almost_ correct.

A similar strategy succeeded in this PR: https://github.com/CliMA/Oceananigans.jl/pull/2412

2022-10-19 19:04 UTC, tomchor commented
> Either way, I don't think that's important. A preconditioner should be some kind of approximate inverse for A, where we are solving for x in Ax = b --- or in other words, an approximate solver. The preconditioner does not have to be "exact" or "error free", since it's really the CG iteration that solves the problem. The idea is that the FFT-based solver yields a pressure field that is _almost_ correct.

Ah, I see, so the idea behind using the FFT-based solver specifically as a preconditioner is because it's probably faster than other combination (if I understand correctly).

Thanks!

2022-10-19 20:50 UTC, glwagner commented
> > Either way, I don't think that's important. A preconditioner should be some kind of approximate inverse for A, where we are solving for x in Ax = b --- or in other words, an approximate solver. The preconditioner does not have to be "exact" or "error free", since it's really the CG iteration that solves the problem. The idea is that the FFT-based solver yields a pressure field that is _almost_ correct.
> 
> Ah, I see, so the idea behind using the FFT-based solver specifically as a preconditioner is because it's probably faster than other combination (if I understand correctly).
> 
> Thanks!

For sure, and we could use other preconditioners. But I suspect the FFT will be _much_ faster than any other preconditioner, which is why I think it's so interesting (and somewhat novel --- though similar approaches have been used for other problems).

2025-02-28 07:16 UTC, simone-silvestri commented
yep, i ll close

2025-02-28 07:16 UTC, closed without merging