Fix `fkeep` error for `HydrostaticFreeSurfaceModel` with a `HeptadiagonalIterativeSolver`
CliMA/Oceananigans.jl pull request #3190
Opened 2023-07-18 00:00 UTC by iuryt

Removes all support for <1.9 Julia versions and update `Project.toml`.

Closes #3184

2023-07-18 00:42 UTC, simone-silvestri commented
while we are at it we can also change

https://github.com/CliMA/Oceananigans.jl/blob/826bae67689bdac18749911fedb65ff83bd55ec2/src/Fields/field.jl#L548-L554

2023-07-18 05:11 UTC, navidcy commented on Project.toml
> +julia = "^1.9"
```suggestion
julia = "1.9"
```

2023-07-18 05:13 UTC, navidcy commented on docs/src/index.md
>      While most scripts will run on Julia 1.6, 1.7, or 1.8, Oceananigans is continuously tested _only_ on Julia 1.9.
```suggestion
   Oceananigans requires Julia 1.9 or later.
```

2023-07-18 05:22 UTC, navidcy commented
@iuryt, in the fields.jl you only needed to remove the branch of the conditional statement that was referring to pre-1.7 versions, not both. E.g., in the [ternary operators](https://docs.julialang.org/en/v1/manual/control-flow/#man-conditional-evaluation):

```Julia
check_version_larger_than_7() = VERSION.minor > 7

initialize_a_field!(::SumReduction,  f, r, c) = check_version_larger_than_7() ? do_this_if_minor > 7 : do_this_if_minor <= 7
```

I fixed it. Let's see if tests pass now!

2023-07-18 05:25 UTC, navidcy requested changes
this is a breaking change so let's bump up a minor release
@iuryt, could you bump up the minor version number in the Project.toml?

https://github.com/iuryt/Oceananigans.jl/blob/ef5e0aa1a8130f26117d06b82d6b8eba420e384f/Project.toml#L4

2023-07-18 05:51 UTC, navidcy commented on README.md
> +1. [Download Julia](https://julialang.org/downloads/) (version 1.9 or higher).
```suggestion
1. [Download Julia](https://julialang.org/downloads/) (version 1.9 or later).
```

2023-07-18 07:13 UTC, navidcy commented
> this is a breaking change so let's bump up a minor release @iuryt, could you bump up the minor version number in the Project.toml?
> 
> https://github.com/iuryt/Oceananigans.jl/blob/ef5e0aa1a8130f26117d06b82d6b8eba420e384f/Project.toml#L4

Also, when this happens, rename the PR to add the new version in front; see [#3147](https://github.com/CliMA/Oceananigans.jl/issues/3147#issuecomment-1595628085).

2023-07-18 12:11 UTC, navidcy approved these changes

2023-07-18 14:33 UTC, merged

2023-07-19 19:10 UTC, iuryt commented
Hi, is that expected that the docs is not yet updated?

https://clima.github.io/OceananigansDocumentation


For me, it is still showing that you could use 1.6

![image](https://github.com/CliMA/Oceananigans.jl/assets/5797727/fc26483d-0518-4bb0-b399-bae80d6e3345)

2023-07-19 19:55 UTC, navidcy commented
See https://github.com/CliMA/Oceananigans.jl/issues/3191