Update quick_start.md
CliMA/Oceananigans.jl pull request #3551
Opened 2024-04-11 19:19 UTC by greenca

Fixing an error in the quick start code: set!(model, u=\epsilon, v=\epsilon) fails if the function \epsilon only has two arguments. Code runs if a third argument is added to the \epsilon definition.

2024-04-12 08:33 UTC, navidcy commented
Hm.... what version of Oceananigans did you try the quick_start example with? I'd bet you used a very old version, e.g., a version _before_ the breaking release [v0.90.0](https://github.com/CliMA/Oceananigans.jl/releases/tag/v0.90.0)?

The quick start example works on `main` for me:

```julia
julia> using Oceananigans
Precompiling Oceananigans
  1 dependency successfully precompiled in 12 seconds. 160 already precompiled.
[ Info: Oceananigans will use 8 threads

julia> grid = RectilinearGrid(size=(128, 128), x=(0, 2π), y=(0, 2π), topology=(Periodic, Periodic, Flat))
128×128×1 RectilinearGrid{Float64, Periodic, Periodic, Flat} on CPU with 3×3×0 halo
├── Periodic x ∈ [-7.51279e-18, 6.28319) regularly spaced with Δx=0.0490874
├── Periodic y ∈ [-7.51279e-18, 6.28319) regularly spaced with Δy=0.0490874
└── Flat z

julia> model = NonhydrostaticModel(; grid, advection=WENO())
NonhydrostaticModel{CPU, RectilinearGrid}(time = 0 seconds, iteration = 0)
├── grid: 128×128×1 RectilinearGrid{Float64, Periodic, Periodic, Flat} on CPU with 3×3×0 halo
├── timestepper: QuasiAdamsBashforth2TimeStepper
├── advection scheme: WENO reconstruction order 5
├── tracers: ()
├── closure: Nothing
├── buoyancy: Nothing
└── coriolis: Nothing

julia> ϵ(x, y) = 2rand() - 1
ϵ (generic function with 1 method)

julia> set!(model, u=ϵ, v=ϵ)

julia> simulation = Simulation(model; Δt=0.01, stop_iteration=100)
Simulation of NonhydrostaticModel{CPU, RectilinearGrid}(time = 0 seconds, iteration = 0)
├── Next time step: 10 ms
├── Elapsed wall time: 0 seconds
├── Wall time per iteration: NaN days
├── Stop time: Inf days
├── Stop iteration : 100.0
├── Wall time limit: Inf
├── Callbacks: OrderedDict with 4 entries:
│   ├── stop_time_exceeded => Callback of stop_time_exceeded on IterationInterval(1)
│   ├── stop_iteration_exceeded => Callback of stop_iteration_exceeded on IterationInterval(1)
│   ├── wall_time_limit_exceeded => Callback of wall_time_limit_exceeded on IterationInterval(1)
│   └── nan_checker => Callback of NaNChecker for u on IterationInterval(100)
├── Output writers: OrderedDict with no entries
└── Diagnostics: OrderedDict with no entries

julia> run!(simulation)
[ Info: Initializing simulation...
[ Info:     ... simulation initialization complete (60.129 ms)
[ Info: Executing initial time step...
[ Info:     ... initial time step complete (1.811 seconds).
[ Info: Simulation is stopping after running for 2.079 seconds.
[ Info: Model iteration 100 equals or exceeds stop iteration 100.
```

Also, in [the docs](https://clima.github.io/OceananigansDocumentation/dev/quick_start/) the example runs every time the docs are built, so if it was broken you wouldn't see the output below the the simulation ran.

2024-04-12 08:37 UTC, navidcy requested changes
I believe you tested the quick start example with a version of Oceananigans _before_ the breaking change of [v0.90.0](https://github.com/CliMA/Oceananigans.jl/releases/tag/v0.90.0). Please let us know if that's not the case and the issue still persist with the latest tagged release.

2024-04-12 16:42 UTC, greenca commented
My apologies. I installed using Pkg.add and assumed it would give me the latest version. I've updated the version and that solved the problem. Thanks for looking into it!

2024-04-12 16:42 UTC, closed without merging

2024-04-13 07:51 UTC, navidcy commented
No worries! Probably you didn't get the latest version installed because of a compat requirement from another package you had installed in the same environment.

2024-04-16 21:56 UTC, glwagner commented
Thanks for the PR even though it wasn't needed!