Generalizes halo filling for flux boundary conditions
CliMA/Oceananigans.jl pull request #904
Opened 2020-09-03 08:28 UTC by glwagner

This PR generalizes `fill_halo_regions!` for flux boundary conditions to work correctly for biharmonic diffusivities, in addition to second-order diffusivities. It also does some minor shuffling of file content and names.

2020-09-03 11:26 UTC, ali-ramadhan requested changes
> In particular (and after tweaking the definition of `AnisotropicBiharmonicDiffusivity`), no flux conditions on any even diffusion operator are enforced by ensuring that odd derivatives across the boundary are zero. This was already done for the first derivative, but did not work for third derivatives and higher. In this PR, kernels are written that reflect fields across the boundary for flux boundary conditions. Reflection implies that odd derivatives are zero and ensures that no flux is enforced for diffusivities of order higher than two.

Am I right in understanding that now `_fill_*_halo!(c, ::FBC, H, N)` is called for all flux boundary conditions but is only required if running with biharmonic diffusivity (or other higher-order diffusivity closures)?

If so, it seems that the vast majority of models will be launching extra kernels (small performance hit) if they have flux boundary conditions. We should open an issue about fixing this potential performance hit.

> Note that `Value` and `Gradient` boundary conditions do not work for biharmonic diffusivity (and likely never will). Thus only `Flux` and `Periodic` boundary conditions are supported with biharmonic diffusivity.

Should we add a warning somewhere in case a user decides to use biharmonic diffusivity with `Value` or `Gradient` boundary conditions, or is biharmonic diffusivity still an experimental feature?

---

Couple of tests failing due to `type AnisotropicBiharmonicDiffusivity has no field κh`: https://travis-ci.com/github/CliMA/Oceananigans.jl/jobs/380678166#L509-L515

And the Eady turbulence example needs to be fixed.

2020-09-03 11:26 UTC, ali-ramadhan commented on src/TurbulenceClosures/turbulence_closure_implementations/anisotropic_biharmonic_diffusivity.jl
> +    ∂ᵢ κᵢⱼ ∂ⱼc = - (κh ∂⁴x + ∂⁴y + κz ∂⁴z) c
Should probably be
```
∂ᵢ κᵢⱼ ∂ⱼ c = - (κx ∂⁴x + κy ∂⁴y + κz ∂⁴z) c
```

2020-09-03 11:37 UTC, glwagner commented
We have always launched a kernel for flux bcs! Previously we used broadcasting. When the halo size was greater than 1, the intent of the broadcast operation was violated. This PR corrects that.

Some informal benchmarks suggest that a KernelAbstractions kernel  can be more efficient than using GPUArrays broadcasting. We can also use multi threading. Thus I would expect speed up from this change, rather than slowdown (but likely negligible speed up). But of course benchmarking is a good idea.

Another advantage is that we can utilize KernelAbstractions dependency feature more fully if we get to the point where we do not use broadcasting for anything. We haven't optimized our dependency structure, however. Also, there are a few puzzles to be worked out regarding periodic boundary conditions before we can convert the periodic halo filling to kernels.

2020-09-03 13:02 UTC, ali-ramadhan approved these changes
Ah I see, right. I agree more kernels would be nice here. Don't think broadcasting is multithreaded?

> Note that `Value` and `Gradient` boundary conditions do not work for biharmonic diffusivity (and likely never will).

I think we should mention this to users somewhere (warning and/or docstring, or documentation).

Otherwise looks good to merge once tests pass.

2020-09-03 14:39 UTC, glwagner commented
> I think we should mention this to users somewhere (warning and/or docstring, or documentation).

I agree. I should clarify too. One reason that biharmonic is more complicated is we need more than one boundary condition. This PR actually modifies the `Flux` boundary condition so that it applies multiple boundary conditions (the same number as the number of halos) in order to enforce zero diffusive flux (for the diffusion operators we support --- our method is not general mathematically). With `Value` and `Gradient` we would need the user to provide another boundary condition to fully specify the problem. The one situation where this might make sense is in the case of an open boundary condition with non zero `NormalFlow`. In that case one might wish to specify a `Value` and then perhaps also another condition. It's worth some thought and perhaps reading in the literature...

For now, I will implement an error.

2020-09-03 18:58 UTC, merged

2020-09-04 13:51 UTC, ali-ramadhan commented on src/TurbulenceClosures/turbulence_closure_implementations/anisotropic_biharmonic_diffusivity.jl
> +    ∂ᵢ κᵢⱼ ∂ⱼc = - (κh ∂⁴x + ∂⁴y + κz ∂⁴z) c
You ignored my suggestion :(

2020-09-04 14:29 UTC, glwagner commented on src/TurbulenceClosures/turbulence_closure_implementations/anisotropic_biharmonic_diffusivity.jl
> +    ∂ᵢ κᵢⱼ ∂ⱼc = - (κh ∂⁴x + ∂⁴y + κz ∂⁴z) c
bahhh sorry about that